### PR TITLE
Fixed text vanishing when the transform is vertically flipped

### LINKED ISSUE #600: Text vanishes when transformation is flipped
It's easy to reproduce, the [Gist](https://gist.github.com/mulle-kybernetik-tv/2a25b045e47a67026df8139d7cf18aa4) has the full modified example file. 

```
      // flip
#if 0
      nvgScale( vg, 1.0, -1.0);
      nvgTranslate( vg, 0,- winHeight);
#endif      
      // triangle
      nvgBeginPath ( vg );
      nvgMoveTo ( vg, winWidth/ 2.0, 0.0);
      nvgLineTo ( vg, winWidth, winHeight );
      nvgLineTo ( vg, 0.0, winHeight);
      nvgLineTo ( vg, winWidth/ 2.0, 0.0);
      nvgFillColor(vg, nvgHSLA(i/19.0f, 0.5f, 0.5f, 255));
      nvgFill(vg);

      // text
      nvgFontFace( vg, "sans");
      nvgFontSize( vg, 64);
      nvgFillColor( vg, nvgRGBA(0,0,0,255)); // TODO: use textColor
      nvgText( vg, winWidth / 2.0, winHeight / 3.0, "AY", NULL);
      nvgEndFrame(vg);

```

normal

If you enable the flip, then the text vanishes:

flipped

I kinda expected it not to.

### PR DESCRIPTION
**Pull request by mulle-nat**
Fixes #600.

### CODE REVIEW

File: src/nanovg.c [hunk 1]
```diff
@@ -2454,6 +2454,12 @@ static void nvg__renderText(NVGcontext* ctx, NVGvertex* verts, int nverts)
 	ctx->textTriCount += nverts/3;
 }
 
+static int   nvg__isTransformFlipped( const float *xform)
```
Comment (memononen) [inline src/nanovg.c:2457]: Please copy the formatting from the surrounding code. Function def and return.

File: src/nanovg.c [hunk 2]
```diff
@@ -2464,6 +2470,8 @@ float nvgText(NVGcontext* ctx, float x, float y, const char* string, const char*
 	float invscale = 1.0f / scale;
 	int cverts = 0;
 	int nverts = 0;
+	int isFlipped;
```
Comment (memononen) [inline src/nanovg.c:2473]: set to `nvg__isTransformFlipped( state->xform)` directly here.

File: src/nanovg.c [hunk 3]
```diff
@@ -2497,6 +2506,11 @@ float nvgText(NVGcontext* ctx, float x, float y, const char* string, const char*
 				break;
 		}
 		prevIter = iter;
+		if( isFlipped)
+		{
+			tmp = q.y0; q.y0 = q.y1; q.y1 = tmp;
```
Comment (memononen) [inline src/nanovg.c:2511]: Move tmp definition at the beginning of the block here.

File: src/nanovg.c [hunk 4]
```diff
@@ -2497,6 +2506,11 @@ float nvgText(NVGcontext* ctx, float x, float y, const char* string, const char*
 				break;
 		}
 		prevIter = iter;
+		if( isFlipped)
```
Comment (memononen) [inline src/nanovg.c:2509]: space after if, not after paren, curly on the same line.

File: src/nanovg.c [hunk 5]
```diff
@@ -2480,6 +2488,7 @@ float nvgText(NVGcontext* ctx, float x, float y, const char* string, const char*
 	verts = nvg__allocTempVerts(ctx, cverts);
 	if (verts == NULL) return x;
 
+	isFlipped = nvg__isTransformFlipped( state->xform);
```
Comment (memononen) [inline src/nanovg.c:2491]: remove space after paren

**Review by memononen — CHANGES_REQUESTED** [review]
Few fixes, mostly style.

**Comment by memononen** [comment]
Thanks for the fix!
